apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elastic-operator
spec:
  hosts:
    - elk.onemesh.anthos.val.arkea-gcp.net
  gateways:
    - istio-ingressgateway/istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /elk
      route:
        - destination:
            host: elastic-operator
